# Use the official PostgreSQL image from Docker Hub
FROM postgres:latest

# Set environment variables for PostgreSQL
ENV POSTGRES_USER=daria
ENV POSTGRES_PASSWORD=daria1234
ENV POSTGRES_DB=products

# Expose the PostgreSQL port
EXPOSE 5432